services:
  backend:
    image: backend-prod
    build:
      context: ./backend/
      network: host
      dockerfile: Dockerfile
    env_file:
      - path: ./backend/.env-backend
        required: true
    volumes:
      - ./backend/:/usr/src/backend
    container_name: backend-prod-1
    networks:
      custom-network:
        ipv4_address: 10.2.0.4
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_started
  mongo:
    image: mongo
    env_file:
      - path: ./backend/.env-backend
        required: true
    volumes:
      - ./backend/src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/mongo/data
    container_name: mongo
    networks:
      custom-network:
        ipv4_address: 10.2.0.5
  nginx:
    image: proxy-server-prod
    build:
      context: ./frontend/
      network: host
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # ro for read-only
    ports:
      - '8000:80'
    container_name: reverse-proxy-prod
    networks:
      custom-network:
        ipv4_address: 10.2.0.3
    depends_on:
      backend:
        condition: service_started
networks:
  custom-network:
    external: true
